apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dgse.fullname" . }}
  labels:
    {{- include "dgse.labels" . | nindent 4 }}
data:
  DRONE_BIND: {{ .Values.config.DRONE_BIND | b64enc }}
  DRONE_DEBUG: {{ .Values.config.DRONE_DEBUG | b64enc }}
  DRONE_SECRET: {{ .Values.config.DRONE_SECRET | b64enc }}
  GITEA_URL: {{ .Values.config.GITEA_URL | b64enc }}
  GITEA_USERNAME: {{ .Values.config.GITEA_USERNAME | b64enc }}
  GITEA_PASSWORD: {{ .Values.config.GITEA_PASSWORD | b64enc }}
  GITEA_DRONE_TOKEN_TTL: {{ .Values.config.GITEA_DRONE_TOKEN_TTL | b64enc }}
  GITEA_DRONE_TOKEN_PREFIX: {{ .Values.config.GITEA_DRONE_TOKEN_PREFIX | b64enc }}
  GITEA_DRONE_TOKEN_GC_ENABLE: {{ .Values.config.GITEA_DRONE_TOKEN_GC_ENABLE | b64enc }}
