apiVersion: v1
description: Drone Gitea Extensions Deployment
name: dgse
version: 0.0.1
appVersion: 0.0.1
keywords:
- drone
- gitea
- secret
- secret extension
- registry extension
- environment extension
- build credentials
- build package api
- docker registry
home: https://github.com/davidhiendl/drone-gitea-extensions
# icon: https://....
sources:
- https://github.com/davidhiendl/drone-gitea-extensions
maintainers:
- name: David Hiendl
  email: david.hiendl@dhswt.de
